### ISSUE TITLE
Yarn build 시 SITE_ROOT 초기화 실패가 뜨는데 이부분은 어디에 경로를 넣어야할까요?

### ISSUE THREAD

**Issue by 78963l** [studio2l/elo#23]
Npm start 시에는
Elo.js 에서 process.env.SITE_ROOT에 경로를 정해줬었습니다.

**Comment by kybin** [comment]
yarn build 명령을 실행할 때 에러가 난단 말씀이신가요? 
아니면 yarn build로 생성한 파일로 프로그램을 실행했을때 에러가 난단 말씀이신가요? 

만약 후자라면 환경변수를 잡아주어야 하는데 이는 OS마다 약간씩 다릅니다.
만일 윈도우즈라면 '유저 환경변수'나 '시스템 환경변수' 에서 잡아주면 되구요.
리눅스라면 상황에 따라 .profile, .bashrc, /etc/profile, ... 중 한 곳에 환경변수를 설정해주면 됩니다.

**Comment by 78963l** [comment]
> yarn build 명령을 실행할 때 에러가 난단 말씀이신가요?
> 아니면 yarn build로 생성한 파일로 프로그램을 실행했을때 에러가 난단 말씀이신가요?
> 
> 만약 후자라면 환경변수를 잡아주어야 하는데 이는 OS마다 약간씩 다릅니다.
> 만일 윈도우즈라면 '유저 환경변수'나 '시스템 환경변수' 에서 잡아주면 되구요.
> 리눅스라면 상황에 따라 .profile, .bashrc, /etc/profile, ... 중 한 곳에 환경변수를 설정해주면 됩니다.

+2
