### ISSUE TITLE
macOS에서 실제로 아래 창이 뜨고 실행되지 않음.

### ISSUE THREAD

**Issue by khw7096** [studio2l/elo#9]
![image](https://user-images.githubusercontent.com/1149996/58970419-5d623d00-87f4-11e9-8a3f-6e09121ce7e7.png)

**Comment by khw7096** [comment]
일반적으로 `.app` 확장자를 사용하기 때문에 변경해봄.

**Comment by khw7096** [comment]
아이콘 모양이 실행파일 형식처럼 아래 모양으로 바뀜.

![image](https://user-images.githubusercontent.com/1149996/58970526-926e8f80-87f4-11e9-9aa3-ccdbd52fcb51.png)

**Comment by khw7096** [comment]
그래도 실행되진 않음.

![image](https://user-images.githubusercontent.com/1149996/58970543-9d292480-87f4-11e9-8dd9-1c89790c8445.png)

**Comment by kybin** [comment]
아, 앱이미지는 리눅스 실행파일이에요..

**Comment by khw7096** [comment]
알겠어요. 저에게 눈앞에서 "안쓰기만 해봐요. 올렸어요!" 라고 해서... 맥용인줄!! ㅋㅋ

**Comment by khw7096** [comment]
직접  macOS 에서 빌드테스트를 진행.
